project:
  type: website
  output-dir: docs
  resources:
    - "verification-follow_it-ulPT3JDlE14h1rCzE2p6.html"
website:
  title: "British Coast"
  site-url: https://shug0131.github.io/coastline/
  description: "Cycle Tour of the British Coast"
  navbar:
    primary: true
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
    right:
      - icon: rss
        href: blog.xml
  margin-header: subscribe.html  
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
